spring:
  application:
    name: noteservice-eureka-client
server:
  port: 1996
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    
